version: '2.2'
services:
  intermediate:
    image: gficentreouest/alpine-cfssl
    init: true
    restart: ${DOCKER_DEVBOX_RESTART_POLICY}
    environment:
      - CFSSL_CSR=csr_intermediate_ca.json
      - CFSSL_CONFIG=ca_intermediate_config.json
      - DB_DISABLED=1
      - VIRTUAL_HOST=${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}
      - VIRTUAL_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}"
      - "traefik.port=80"
    ports:
      - "${DOCKER_DEVBOX_PORT_PREFIX}80:80"
    networks:
      - default
      - reverse-proxy
    volumes:
      - "intermediate:/etc/cfssl"
networks:
  reverse-proxy:
    external: true
    name: ${DOCKER_DEVBOX_REVERSE_PROXY_NETWORK}
volumes:
  intermediate:
