version: '2.2'
services:
  root:
    build:
      context: .docker
      dockerfile: docker-alpine-cfssl/Dockerfile
    image: ${DOCKER_DEVBOX_REGISTRY}cfssl/root
    init: true
    restart: ${DOCKER_DEVBOX_RESTART_POLICY}
    environment:
      - CFSSL_CSR=csr_root_ca.json
      - CFSSL_CONFIG=ca_root_config.json
      - DB_DISABLED=1
    volumes:
      - "root:/etc/cfssl"
  intermediate:
    build:
      context: .docker
      dockerfile: docker-alpine-cfssl/Dockerfile
    image: ${DOCKER_DEVBOX_REGISTRY}cfssl/intermediate
    init: true
    restart: ${DOCKER_DEVBOX_RESTART_POLICY}
    depends_on:
      - root
    environment:
      - CFSSL_CSR=csr_intermediate_ca.json
      - CFSSL_CONFIG=ca_intermediate_config.json
      - CA_ROOT_URI=http://root.${COMPOSE_NETWORK_NAME}
      - DB_DISABLED=1
    volumes:
      - "intermediate:/etc/cfssl"
volumes:
  root:
  intermediate: