version: '2.2'
services:
  root:
    image: gficentreouest/alpine-cfssl
    init: true
    restart: ${DOCKER_DEVBOX_RESTART_POLICY}
    environment:
      - CFSSL_CSR=csr_root_ca.json
      - CFSSL_CONFIG=ca_root_config.json
      - DB_DISABLED=1
    volumes:
      - "root:/etc/cfssl"
      - "root_trust:/cfssl_trust"
  intermediate:
    image: gficentreouest/alpine-cfssl
    init: true
    restart: ${DOCKER_DEVBOX_RESTART_POLICY}
    depends_on:
      - root
    ports:
      - "${DOCKER_DEVBOX_PORT_PREFIX}80:80"
    environment:
      - CFSSL_CSR=csr_intermediate_ca.json
      - CFSSL_CONFIG=ca_intermediate_config.json
      - CA_ROOT_URI=http://root.${COMPOSE_NETWORK_NAME}
      - DB_DISABLED=1
    volumes:
      - "intermediate:/etc/cfssl"
      - "intermediate_trust:/cfssl_trust"
volumes:
  root:
  root_trust:
  intermediate:
  intermediate_trust:
