version: '3.7'
services:
  intermediate:
    image: gficentreouest/alpine-cfssl
    init: true
    restart: ${DOCKER_DEVBOX_RESTART_POLICY}
    environment:
      - CFSSL_CSR=csr_intermediate_ca.json
      - CFSSL_CONFIG=ca_intermediate_config.json
      - DB_DISABLED=1
    ports:
      - "${DOCKER_DEVBOX_PORT_PREFIX}80:80"
    networks:
      - default
      - reverse-proxy
    volumes:
      - "intermediate:/etc/cfssl"
volumes:
  intermediate:
