networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
services:
  intermediate:
    environment:
    - CFSSL_CSR=csr_intermediate_ca.json
    - CFSSL_CONFIG=ca_intermediate_config.json
    - DB_DISABLED=1
    expose:
    - 80
    image: gficentreouest/alpine-cfssl
    init: true
    labels:
      ddb.emit.certs:generate: cfssl.test
      traefik.enable: 'true'
      traefik.http.routers.cfssl-tls.rule: Host(`cfssl.test`)
      traefik.http.routers.cfssl-tls.service: cfssl
      traefik.http.routers.cfssl-tls.tls: 'true'
      traefik.http.routers.cfssl.rule: Host(`cfssl.test`)
      traefik.http.routers.cfssl.service: cfssl
      traefik.http.services.cfssl.loadbalancer.server.port: 80
    networks:
    - default
    - reverse-proxy
    ports:
    - 7780:80
    restart: 'no'
    volumes:
    - intermediate:/etc/cfssl
    - intermediate_trust:/cfssl_trust
version: '3.7'
volumes:
  intermediate: {}
  intermediate_trust: {}
