version: "2"
services:
  root:
    build:
      context: docker-alpine-cfssl
      args:
       http_proxy: ${http_proxy}
       https_proxy: ${https_proxy}
       no_proxy: ${no_proxy}
    environment:
      - CFSSL_CSR=csr_root_ca.json
      - CFSSL_CONFIG=ca_root_config.json
      - DB_CONFIG=db_config.json
    volumes:
      - "./root:/etc/cfssl"
    restart: unless-stopped
  intermediate:
    build:
      context: docker-alpine-cfssl
      args:
       http_proxy: ${http_proxy}
       https_proxy: ${https_proxy}
       no_proxy: ${no_proxy}
    depends_on:
      - root
    ports:
      - "8080:8080"
    environment:
      - CFSSL_CSR=csr_intermediate_ca.json
      - CFSSL_CONFIG=ca_intermediate_config.json
      - CA_ROOT_URI=http://root:8080
      - DB_CONFIG=db_config.json
    volumes:
      - "./intermediate:/etc/cfssl"
    restart: unless-stopped