version: '2.2'
services:
  root:
    build:
      context: .docker
      dockerfile: cfssl/Dockerfile
    init: true
    user: '${USER_ID}:${GROUP_ID}'
    restart: ${DOCKER_DEVBOX_RESTART_POLICY}
    environment:
      - CFSSL_CSR=csr_root_ca.json
      - CFSSL_CONFIG=ca_root_config.json
      - DB_DISABLED=1
    volumes:
      - "root:/etc/cfssl"
      - "${DOCKER_DEVBOX_CERTS_PATH}/cfssl-ca:/rootca"
  intermediate:
    build:
      context: .docker
      dockerfile: cfssl/Dockerfile
    init: true
    user: '${USER_ID}:${GROUP_ID}'
    restart: ${DOCKER_DEVBOX_RESTART_POLICY}
    depends_on:
      - root
    ports:
      - "${DOCKER_DEVBOX_PORT_PREFIX}80:80"
    environment:
      - CFSSL_CSR=csr_intermediate_ca.json
      - CFSSL_CONFIG=ca_intermediate_config.json
      - CA_ROOT_URI=http://root.${COMPOSE_NETWORK_NAME}
      - DB_DISABLED=1
      - VIRTUAL_HOST=${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}
    networks:
      - default
      - reverse-proxy
    volumes:
      - "intermediate:/etc/cfssl"
networks:
  reverse-proxy:
    external: true
    name: ${DOCKER_DEVBOX_REVERSE_PROXY_NETWORK}
volumes:
  root:
  intermediate: