version: "2"
networks:
  nginx-proxy:
    external: true
services:
  intermediate:
    environment:
      VIRTUAL_HOST: ${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}
    networks:
      - default
      - nginx-proxy
    ports:
      - "${DOCKER_DEVBOX_PORT_PREFIX}88:8888"